apiVersion: batch/v1
kind: Job
metadata:
  name: sqlite-restore
  namespace: pra
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: alpine
          env:
            - name: BACKUP_NAME
              value: ""
          command: ["/bin/sh","-c"]
          args:
            - |
              if [ -z "$BACKUP_NAME" ]; then
                TARGET=$(ls -t /backup/*.db | head -1)
                echo "Restauration du dernier backup : $TARGET"
              else
                TARGET="/backup/$BACKUP_NAME"
                echo "Restauration du point spécifique : $TARGET"
              fi
              cp "$TARGET" /data/app.db
          volumeMounts:
            - name: data
              mountPath: /data
            - name: backup
              mountPath: /backup
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pra-data
        - name: backup
          persistentVolumeClaim:
            claimName: pra-backup